# Generated by Django 3.2.3 on 2021-05-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('identity', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=5, verbose_name='性别')),
                ('ethnicity', models.CharField(max_length=20, verbose_name='民族')),
                ('nationality', models.CharField(max_length=10, verbose_name='国籍')),
                ('address', models.CharField(max_length=200, verbose_name='住址')),
                ('telephone', models.CharField(max_length=15, verbose_name='固定电话')),
                ('mobile', models.CharField(max_length=25, verbose_name='手机号码')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '驾驶员/车主信息',
                'verbose_name_plural': '驾驶员/车主信息',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('engine_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='发动机编号')),
                ('brand', models.CharField(max_length=25, verbose_name='品牌')),
                ('manufacture_model', models.CharField(max_length=35, verbose_name='型号')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('vehicle_type', models.CharField(choices=[('A', '载货汽车'), ('B', '越野汽车'), ('C', '自卸汽车'), ('D', '牵引车'), ('E', '专用汽车'), ('F', '客车'), ('G', '轿车'), ('H', '半挂车'), ('K', '其它')], max_length=2, verbose_name='车型')),
                ('displacement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='排量')),
                ('manufacture_date', models.DateField(verbose_name='出厂日期')),
                ('life_duration', models.PositiveIntegerField(verbose_name='使用年限（年）')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号码')),
                ('status', models.CharField(choices=[('A', 'A-正常'), ('B', 'B-转出'), ('C', 'C-被盗抢'), ('D', 'D-停驶'), ('E', 'E-注销'), ('G', 'F-违法未处理'), ('H', 'H-海关监管'), ('I', 'I-事故未处理'), ('J', 'J-嫌疑车'), ('K', 'K-查封'), ('L', 'L-暂扣'), ('M', 'M-强制注销'), ('N', 'N-事故逃逸'), ('O', 'O-锁定'), ('F', 'F-退车')], default='A', max_length=8, verbose_name='机动车状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficMan.userprofile')),
            ],
            options={
                'verbose_name': '机动车信息',
                'verbose_name_plural': '机动车信息',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrafficMan.userprofile')),
                ('issue_date', models.DateField(verbose_name='驾驶证初次领证日期')),
                ('motor_type', models.CharField(choices=[('A1', 'A1-大型客车'), ('A2', 'A2-牵引车'), ('A3', 'A3-城市公交车'), ('B1', 'B1-中型客车'), ('B2', 'B2-大型货车'), ('C1', 'C1-小型汽车'), ('C2', 'C2-小型自动挡汽车'), ('C3', 'C3-低速载货汽车'), ('C4', 'C4-三轮汽车'), ('C5', 'C5-残疾人专用小型自动挡载客汽车'), ('D', 'D-普通三轮摩托车'), ('E', 'E-普通二轮摩托车'), ('F', 'F-轻便摩托车'), ('M', 'M-轮式自行机械车'), ('N', 'N-无轨电车'), ('P', 'P-有轨电车')], max_length=3, verbose_name='驾驶证准驾车型')),
                ('begin_date', models.DateField(verbose_name='驾驶证有效起始日期')),
                ('valid_duration', models.PositiveIntegerField(verbose_name='驾驶证有效年限（年）')),
                ('points', models.IntegerField(default=12, verbose_name='驾驶证分数')),
                ('status', models.CharField(choices=[('A', 'A-正常'), ('B', 'B-超分'), ('C', 'C-转出'), ('D', 'D-暂扣'), ('E', 'E-撤销'), ('F', 'F-吊销'), ('G', 'G-注销'), ('H', 'H-违法未处理'), ('J', 'J-停止使用')], default='A', max_length=5, verbose_name='驾驶证状态')),
            ],
            options={
                'verbose_name': '驾驶证信息',
                'verbose_name_plural': '驾驶证信息',
            },
        ),
        migrations.CreateModel(
            name='VehicleLicense',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrafficMan.vehicle')),
                ('usage', models.CharField(max_length=20, verbose_name='使用性质')),
                ('registration_date', models.DateField(verbose_name='注册日期')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
            ],
            options={
                'verbose_name': '行驶证信息',
                'verbose_name_plural': '行驶证信息',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='违章时间')),
                ('type', models.CharField(max_length=30, verbose_name='违章类型')),
                ('area', models.CharField(max_length=50, verbose_name='区域')),
                ('location', models.CharField(max_length=50, verbose_name='位置')),
                ('point_minus', models.PositiveIntegerField(verbose_name='扣分')),
                ('fine', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='罚款')),
                ('deadline', models.DateTimeField(verbose_name='罚款缴纳截至日期')),
                ('is_processed', models.BooleanField(verbose_name='是否已缴纳')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficMan.userprofile')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficMan.vehicle', to_field='plate_number')),
            ],
            options={
                'verbose_name': '违章信息',
                'verbose_name_plural': '违章信息',
            },
        ),
    ]
