# Generated by Django 3.2.3 on 2021-05-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0002_auto_20210526_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violationprocess',
            options={'verbose_name': '违章处理记录查询', 'verbose_name_plural': '违章处理记录查询'},
        ),
    ]
