# Generated by Django 3.2.3 on 2021-05-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0004_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationprocess',
            name='id',
        ),
        migrations.AlterField(
            model_name='violationprocess',
            name='violation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrafficMan.violation', verbose_name='违章编号'),
        ),
    ]
