# Generated by Django 3.2.3 on 2021-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0005_auto_20210527_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationProcessRecordView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='违章时间')),
                ('type', models.CharField(max_length=100, verbose_name='违章类型')),
                ('area', models.CharField(max_length=50, verbose_name='区域')),
                ('location', models.CharField(max_length=50, verbose_name='位置')),
                ('point_minus', models.PositiveIntegerField(verbose_name='扣分')),
                ('fine', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='罚款')),
                ('deadline', models.DateField(verbose_name='罚款缴纳截至日期')),
                ('is_processed', models.BooleanField(verbose_name='是否缴纳')),
                ('driver_id', models.CharField(max_length=25, verbose_name='驾驶员身份证号')),
                ('plate_number_id', models.CharField(max_length=20, verbose_name='车牌号码')),
                ('process_time', models.DateTimeField(verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '违章处理记录查询',
                'verbose_name_plural': '违章处理记录查询',
                'db_table': 'v_violationprocessrecord',
                'managed': False,
            },
        ),
    ]
