# Generated by Django 3.2.3 on 2021-05-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0007_auto_20210531_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='educationrecord',
            name='education',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TrafficMan.education', verbose_name='学习ID'),
        ),
    ]
