# Generated by Django 3.2.3 on 2021-05-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0008_auto_20210531_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='violation',
            name='vehicle_id',
            field=models.ForeignKey(default='plate_number', on_delete=django.db.models.deletion.CASCADE, to='TrafficMan.vehicle', verbose_name='车牌号/车主/机动车VIN号'),
            preserve_default=False,
        ),
    ]
