# Generated by Django 3.2.3 on 2021-05-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficMan', '0009_auto_20210531_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
